# Copyright (C) 2025  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Which Docker image shall be used on the GitLab runner?
image: docker:24.0

# Details about how to connect to the Docker service to run this build.
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:24.0-dind

# Three stages; build, test and deploy (if the tags match the syntax)
stages:
  - build
  - test
  - generate
  - download
  - analyse
  - coverage
  - pages
  - deploy

# Display information before we start the build.
before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# This section describes what shall be done to build the project.
build:
  tags:
    - docker-build
  stage: build
  script:
    - apk update && apk add --no-cache curl git make bash
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p y
    - docker buildx create --name builder --use
    - docker buildx inspect --bootstrap

    - rm -rf logs/csv-prev/
    - docker build . --output . --target copytohost

    - docker buildx build --platform linux/amd64,linux/arm/v7 --tag "$CI_REGISTRY_IMAGE:v0.0.2"  --push -f Dockerfile .
  except: 
    - tags

build-images:
  tags:
    - docker-build
  stage: build
  script:
    - git clone --depth=1 --branch v0.0.4 https://github.com/chalmers-revere/opendlv-video-h264-replay.git
    - sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirror.math.princeton.edu/pub/ubuntu/|g' opendlv-video-h264-replay/Dockerfile # Use a mirror to avoid issues with the default Ubuntu archive
    - docker build -t $CI_REGISTRY_IMAGE/video-h264-replay -f opendlv-video-h264-replay/Dockerfile opendlv-video-h264-replay
    - docker push $CI_REGISTRY_IMAGE/video-h264-replay
    - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE/application .
    - docker push $CI_REGISTRY_IMAGE/application
  
# # Test for steering angle microservice
# test-steering-angle:
#   stage: test
#   image: ubuntu:22.04
#   tags:
#     - docker-build
#   before_script:
#     - DEBIAN_FRONTEND=noninteractive apt update && apt install -y g++ cmake wget curl unzip pkg-config libopencv-dev libprotobuf-dev protobuf-compiler git

#     - mkdir /opt/cluon && cd /opt/cluon
#     - curl -L -o cluon-complete.hpp https://github.com/chrberger/libcluon/releases/download/v0.0.132/libcluon-complete-0.0.132.hpp

#     - git clone https://github.com/chalmers-revere/opendlv-standard-message-set.git
#     - cp opendlv-standard-message-set/*.hpp /usr/local/include/
#   script:
#     - mkdir -p outputs
#     - g++ -std=c++17 -o test_analysis test_analysis.cpp `pkg-config --cflags --libs cluon opencv`
#     - mkdir -p output
#     - for f in recordings/*.rec; do
#         name=$(basename "$f" .rec);
#         ./test_analysis --input="$f" --csv="outputs/$name.csv" --svg="outputs/$name.svg";
#       done
#   artifacts:
#     paths:
#       - outputs/
    
# This section describes how to generate coverage reports
coverage:
  tags:
    - docker-build
  stage: coverage
  image: alpine:latest
  before_script: []
  script:
    - apk update && apk add --no-cache g++ make cmake lcov gcovr py3-pip python3 gzip
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage" -DCMAKE_C_FLAGS="-fprofile-arcs -ftest-coverage" ..
    - make
    - ./helloworld-Runner --success
    - lcov --capture --directory . --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' '*/test/*' --output-file coverage.info
    - genhtml coverage.info --output-directory lcov-report
    - gcovr --root .. --xml-pretty --output coverage.xml
    - gcovr --root .. --html --html-details -o gcovr-report.html
    
    - cp coverage.info ../
    - cp coverage.xml ../
    - cp -r lcov-report ../
    - mkdir -p ../public
    - cp -r lcov-report/* ../public/

    - mkdir -p ../public
    - cp -r lcov-report/* ../public/
  artifacts:
    paths:
      - public
      - coverage.info
      - lcov-report/
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 52 weeks

# To receive a coverage report in the web UI
pages: 
  tags:
    - docker-build
  stage: pages
  script:
    - echo "Publishing coverage report to GitLab Pages"
    - mv public public_temp && mkdir public && mv public_temp/* public/
  dependencies:
    - coverage
  artifacts:
    paths:
      - public 
  only:
    - 9-add-branch-coverage                  

# Generate CSV files for performance analysis
.generate-csv: &generate-csv-template
  tags:
    - docker-build
  stage: generate
  dependencies:
    - build
    - build-images
  script:
    - docker pull $CI_REGISTRY_IMAGE/video-h264-replay
    - docker pull $CI_REGISTRY_IMAGE/application
    - echo "Processing $FILE.rec"
    - docker run -d --rm -ti --net=host --ipc=host -e DISPLAY=$DISPLAY -v /tmp:/tmp -v $(pwd)/recordings:/recordings --name=replay-$FILE $CI_REGISTRY_IMAGE/video-h264-replay --cid=111 --name=img data/$FILE.rec
    - sleep 1
    - docker run -d --net=host --ipc=host -e DISPLAY=$DISPLAY -v /tmp:/tmp --name=application-$FILE $CI_REGISTRY_IMAGE/application:latest --cid=111 --name=img --width=640 --height=480 --output=/opt/$FILE.csv
    - while docker ps | grep -q replay-$FILE; do sleep 1; done
    - mkdir -p ./logs/csv/
    - if [ -f ./logs/csv/$FILE.csv ]; then cp ./logs/csv/$FILE.csv; fi
    - docker cp application-$FILE:./opt/$FILE.csv ./logs/csv/$FILE.csv
    - docker stop application-$FILE || true  && docker rm application-$FILE || true

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-csv"
    paths:
      - ./logs/csv/*.csv
  allow_failure: true

# Apply template to generate CSV files for each recording
generate-csv-144821:
  <<: *generate-csv-template
  variables:
    FILE: 144821

generate-csv-145043:
  <<: *generate-csv-template
  variables:
    FILE: 145043

generate-csv-145233:
  <<: *generate-csv-template
  variables:
    FILE: 145233

generate-csv-145641:
  <<: *generate-csv-template
  variables:
    FILE: 145641

generate-csv-150001:
  <<: *generate-csv-template
  variables:
    FILE: 150001


.download-prev-csv: &download-prev-csv-template
  image: docker:26-cli
  services:
    - name: docker:26-dind
  tags:
    - docker-build
  stage: download
  before_script:
    - apk add --no-cache curl
    
  script:
    - echo "Downloading previous CSV files..."
    - mkdir -p logs/csv-prev
    - PREV_COMMIT=$(git rev-list --first-parent HEAD | sed -n 2p)
    - echo "Fetching artifact from commit $PREV_COMMIT"
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --location --output logs/csv-prev/$FILE.csv "https://git.chalmers.se/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/14-automate-pipeline/raw/logs/csv/$FILE.csv?job=generate-csv-$FILE" || echo "No previous artifact found"

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-csv-prev"
    paths:
      - logs/csv-prev/*.csv
  allow_failure: true

# Download previous CSV files for performance analysis
download-prev-csv-144821:
  <<: *download-prev-csv-template
  variables:
    FILE: 144821

download-prev-csv-145043:
  <<: *download-prev-csv-template
  variables:
    FILE: 145043

download-prev-csv-145233:
  <<: *download-prev-csv-template
  variables:
    FILE: 145233

download-prev-csv-145641:
  <<: *download-prev-csv-template
  variables:
    FILE: 145641

download-prev-csv-150001:
  <<: *download-prev-csv-template
  variables:
    FILE: 150001

# Performance analysis job
analyse:
  image: python:3.10
  tags:
    - docker-build
  stage: analyse
  
  dependencies:
    - generate-csv-144821
    - generate-csv-145043
    - generate-csv-145233
    - generate-csv-145641
    - generate-csv-150001
    - download-prev-csv-144821
    - download-prev-csv-145043
    - download-prev-csv-145233
    - download-prev-csv-145641
    - download-prev-csv-150001

  before_script:
    - pip install pandas matplotlib
    
  script:
    - echo "Generating performance analysis report..."
    - find logs/
    - ls -l ./logs/csv-prev/
    - if [ ! "$(ls -A ./logs/csv)" ]; then echo "No CSV files, exiting..."; exit 1; fi
    - mkdir -p logs/performance-plots
    - python3 microservices/steering-angle-microservice/src/test_analysis.py csv/*.csv --output logs/performance-plots

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-performance-plots"
    paths:
      - logs/performance-plots/*.png
      - logs/csv-prev/*.csv

# This section describes what shall be done to deploy artefacts from the project.
release:
  tags:
    - docker-build
  stage: deploy
  dependencies:
    - build
  script:
    - apk update && apk add --no-cache curl git make bash
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p y
    - docker buildx create --name builder --use
    - docker buildx inspect --bootstrap

    - docker buildx build --platform linux/amd64,linux/arm/v7 --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" --push -f Dockerfile .
  only:
    - /^v\d+\.\d+\.\d+$/
