# Copyright (C) 2025  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Which Docker image shall be used on the GitLab runner?
image: docker:19.03.3

# Details about how to connect to the Docker service to run this build.
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:19.03.3-dind
# Three stages; build, test and deploy (if the tags match the syntax)
stages:
  - build
  - test
  - coverage
  - pages
  - deploy

# Display information before we start the build.
before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# This section describes what shall be done to build the project.
build:
  tags:
    - docker-build
  stage: build
  script:
    - docker build -f Dockerfile .
  except: 
    - tags
# This section describes what shall be done to test the project
test:
  tags:
    - docker-build
  stage: test
  script:
    - apk update && apk add --no-cache g++ make cmake
    - mkdir -p build
    - cd build
    - cmake ..
    - make
    - ./helloworld-Runner --success
  except: 
    - tags

# This section describes how to generate coverage reports
coverage:
  tags:
   - docker-build
  stage: coverage
  image: docker:19.03.3 
  script:
    - apk update && apk add --no-cache g++ make cmake gcovr py3-pip libxml2-dev libxslt-dev python3 python3-dev
    - pip3 install setuptools
    - pip3 install gcovr 
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_FLAGS="--coverage" ..
    - make
    - ./helloworld-Runner --success
    - gcovr --root .. --xml-pretty --output coverage.xml 
    - gcovr --root .. --html --html-details -o coverage.html
    - mkdir -p ../public       
    - cp coverage.html ../public/index.html
  artifacts:
    paths:
      - public
      - build/coverage.html 
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.xml
    expire_in: 52 week
  except:
    - tags

# To receive a coverage report in the web UI
pages: 
  tags:
    - docker-build
  stage: pages
  script:
    - echo "Publishing coverage report to GitLab Pages"
  dependencies:
    - coverage
  artifacts:
    paths:
      - public 
  only:
    - 9-add-branch-coverage                  

# This section describes what shall be done to deploy artefacts from the project.
release:
  tags:
    - docker-build
  stage: deploy
  script:
    - docker build -f Dockerfile -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG"
  only:
    - /^v\d+\.\d+\.\d+$/
