FROM debian:bullseye

LABEL maintainer="Christian Berger <christian.berger@gu.se>"
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip gnuplot g++ make git cmake \
    libcluon-dev libopendlv-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip3 install pandas matplotlib

WORKDIR /opt/project
COPY . .

RUN g++ -std=c++17 -o rec2csv rec2csv.cpp -lcluon -lopendlv

CMD ["/bin/bash"]
